# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 453ed211a679647193f3bed383ebd074030f2ac1c0c598206157283f66d34176229da709cb745f3864985ebd907673c8a523f03c9ee7d49dc8d42762196d32ed

test:
  secret_key_base: 3465c33a57c446a045555e79be47106830d68e4a42bf06f3a3e314c0551c743335adbf9715696fe955d6773049db9c19b190386cf1de705ff46f2f8d224f3677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
